/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppMerchantsRouteImport } from './routes/_app/merchants'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTaxonomyRouteImport } from './routes/_app/taxonomy'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as DevPrimitivesRouteImport } from './routes/dev.primitives'
import { Route as AppDevJobQueueRouteImport } from './routes/_app/dev.job-queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMerchantsRoute = AppMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxonomyRoute = AppTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/_auth/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPrimitivesRoute = DevPrimitivesRouteImport.update({
  id: '/dev/primitives',
  path: '/dev/primitives',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDevJobQueueRoute = AppDevJobQueueRouteImport.update({
  id: '/dev/job-queue',
  path: '/dev/job-queue',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/merchants': typeof AppMerchantsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/taxonomy': typeof AppTaxonomyRoute
  '/transactions': typeof AppTransactionsRoute
  '/signin': typeof AuthSigninRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/job-queue': typeof AppDevJobQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/merchants': typeof AppMerchantsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/taxonomy': typeof AppTaxonomyRoute
  '/transactions': typeof AppTransactionsRoute
  '/signin': typeof AuthSigninRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/dev/job-queue': typeof AppDevJobQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/merchants': typeof AppMerchantsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/taxonomy': typeof AppTaxonomyRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/_app/dev/job-queue': typeof AppDevJobQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/categories'
    | '/dashboard'
    | '/merchants'
    | '/reports'
    | '/settings'
    | '/taxonomy'
    | '/transactions'
    | '/signin'
    | '/dev/primitives'
    | '/dev/job-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/categories'
    | '/dashboard'
    | '/merchants'
    | '/reports'
    | '/settings'
    | '/taxonomy'
    | '/transactions'
    | '/signin'
    | '/dev/primitives'
    | '/dev/job-queue'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/privacy'
    | '/terms'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/merchants'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/taxonomy'
    | '/_app/transactions'
    | '/_auth/signin'
    | '/dev/primitives'
    | '/_app/dev/job-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthSigninRoute: typeof AuthSigninRoute
  DevPrimitivesRoute: typeof DevPrimitivesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/merchants': {
      id: '/_app/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof AppMerchantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/taxonomy': {
      id: '/_app/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof AppTaxonomyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/primitives': {
      id: '/dev/primitives'
      path: '/dev/primitives'
      fullPath: '/dev/primitives'
      preLoaderRoute: typeof DevPrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dev/job-queue': {
      id: '/_app/dev/job-queue'
      path: '/dev/job-queue'
      fullPath: '/dev/job-queue'
      preLoaderRoute: typeof AppDevJobQueueRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMerchantsRoute: typeof AppMerchantsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTaxonomyRoute: typeof AppTaxonomyRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppDevJobQueueRoute: typeof AppDevJobQueueRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMerchantsRoute: AppMerchantsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTaxonomyRoute: AppTaxonomyRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppDevJobQueueRoute: AppDevJobQueueRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthSigninRoute: AuthSigninRoute,
  DevPrimitivesRoute: DevPrimitivesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
