name: Docker Image CI

on:
  # Allow manual triggering
  workflow_dispatch:
  # Run on push
  push:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      # Read the contents of the repository
      contents: read
      # Allow access to the GitHub container registry
      packages: write
      # Add this permission
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: make IMAGE_NAME lowercase
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME@L}" >>${GITHUB_ENV}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          # Use the newer GITHUB_TOKEN
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
