name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/postgres
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Vite+
      uses: voidzero-dev/setup-vp@v1.21.1
      with:
        node-version: "24"
        cache: true

    - name: Install dependencies
      run: vp install

    - name: Apply migrations
      run: vp run --filter server db:migrate

    - name: Test
      run: vp test
